# Site settings
title: (Dys)functional Programmer
email: jon.abourbih@gmail.com
description: >
  (Dys)Functional and other programming topics. My interests lie in Clojure, functional programming topics, code craftsmanship, AI, and cats.
baseurl: ""
url: "https://jonbca.github.io"
twitter_username: jonzo1
github_username:  jonbca

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
