# Site settings
title: Dysfunctional Programming
email: jon.abourbih@gmail.com
description: >
  (Dys)Functional and other programming topics. My interests lie in Clojure, functional programming, artificial intelligence topics, search and cats.
baseurl: ""
url: "https://jonbca.github.io"
twitter_username: jonzo1
github_username:  jonbca

# Build settings
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
